#!/bin/bash

TEST="RepFRExperiment"
INCLUDES="../RepWordGenerator.cs ../ExperimentBase.cs"

echo "Warning, testing manually extracted subsetTestRepFRExperiment.cs"
mcs TestRepFRExperiment.cs subsetTestRepFRExperiment.cs stubsRepWordGenerator.cs ../RepWordGenerator.cs -d:TESTING
#mcs Test"$TEST".cs ../"$TEST".cs $INCLUDES &&
mono Test"$TEST".exe

